# -*- coding: utf-8 -*-
"""HyperParameter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whVkAHH6dF53riOw7KLvnMTQ718hC-Jr
"""

!pip install scikeras tensorflow -q
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.5.2

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from scikeras.wrappers import KerasClassifier

df = pd.read_csv('/content/breast-cancer.csv')

df.head()

print(df.shape)
print(df.columns)

X = df.drop('diagnosis', axis=1)

y = df['diagnosis']

import sklearn
import pandas

print("scikit-learn:", sklearn.__version__)
print("pandas:", pandas.__version__)

scaler = StandardScaler()

X = scaler.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

def create_model(neurons=16, optimizer='adam'):

    model = Sequential()

    model.add(Dense(
        neurons,
        input_dim=X_train.shape[1],
        activation='relu'
    ))

    model.add(Dense(
        1,
        activation='sigmoid'
    ))

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

df = pd.read_csv('/content/breast-cancer.csv')

# Drop unnecessary columns
if 'id' in df.columns:
    df.drop('id', axis=1, inplace=True)

if 'Unnamed: 32' in df.columns:
    df.drop('Unnamed: 32', axis=1, inplace=True)

# Target
y = df['diagnosis'].map({'M':1, 'B':0})

# Features
X = df.drop('diagnosis', axis=1)

print(X.dtypes)

X = X.apply(pd.to_numeric, errors='coerce')

print(X.isnull().sum().sum())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

print(X.dtype)
print(X.shape)

print(y.dtype)
print(y_train.dtype)

y = y.astype('int64')

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(y_train.dtype)
print(y_test.dtype)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

def create_model(neurons=16):

    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(neurons, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

neurons_list = [8,16,32]
batch_sizes = [16,32]
epochs_list = [10,20]

best_accuracy = 0

for neurons in neurons_list:
    for batch in batch_sizes:
        for epochs in epochs_list:

            model = create_model(neurons)

            history = model.fit(
                X_train,
                y_train,
                epochs=epochs,
                batch_size=batch,
                verbose=0
            )

            accuracy = history.history['accuracy'][-1]

            print(
                f"Neurons={neurons}, Batch={batch}, Epochs={epochs}, Accuracy={accuracy:.4f}"
            )

            if accuracy > best_accuracy:
                best_accuracy = accuracy
                best_params = (neurons, batch, epochs)

print("\nBest Parameters:", best_params)
print("Best Accuracy:", best_accuracy)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

def create_model(neurons=16, optimizer='adam'):

    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(neurons, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV

model = KerasClassifier(
    model=create_model,
    verbose=0
)

param_dist = {
    "model__neurons": [8, 16, 32, 64],
    "batch_size": [16, 32, 64],
    "epochs": [10, 20, 30],
    "model__optimizer": ["adam", "rmsprop"]
}

random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=10,
    cv=3,
    random_state=42,
    n_jobs=1
)

random_search.fit(X_train, y_train)

print("Best Parameters:")
print(random_search.best_params_)

print("\nBest Score:")
print(random_search.best_score_)

from sklearn.model_selection import GridSearchCV
from scikeras.wrappers import KerasClassifier

model = KerasClassifier(
    model=create_model,
    verbose=0
)

param_grid = {
    "model__neurons": [8, 16, 32],
    "batch_size": [16, 32],
    "epochs": [10, 20],
    "model__optimizer": ["adam", "rmsprop"]
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,
    n_jobs=1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest Score:")
print(grid_search.best_score_)

best_model = grid_search.best_estimator_

test_accuracy = best_model.score(X_test, y_test)

print("Test Accuracy:", test_accuracy)

!pip install scikeras tensorflow -q

import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input

from scikeras.wrappers import KerasClassifier

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

print(X_train.shape)
print(X_test.shape)

X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

print(X_train.shape)

X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

print(X_train.shape)

def create_cnn(filters=32,
               kernel_size=3,
               optimizer='adam'):

    model = Sequential([
        Input(shape=(28,28,1)),

        Conv2D(
            filters=filters,
            kernel_size=(kernel_size, kernel_size),
            activation='relu'
        ),

        MaxPooling2D(pool_size=(2,2)),

        Flatten(),

        Dense(128, activation='relu'),

        Dense(10, activation='softmax')
    ])

    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

filters_list = [16, 32]
batch_sizes = [32, 64]
epochs_list = [2, 3]

best_accuracy = 0

for filters in filters_list:

    for batch in batch_sizes:

        for epochs in epochs_list:

            model = create_cnn(filters=filters)

            history = model.fit(
                X_train,
                y_train,
                validation_split=0.2,
                epochs=epochs,
                batch_size=batch,
                verbose=0
            )

            acc = max(history.history['val_accuracy'])

            print(
                f"Filters={filters}, Batch={batch}, Epochs={epochs}, Accuracy={acc:.4f}"
            )

            if acc > best_accuracy:
                best_accuracy = acc
                best_params = (
                    filters,
                    batch,
                    epochs
                )

print("\nBest Parameters:", best_params)
print("Best Accuracy:", best_accuracy)

cnn_model = KerasClassifier(
    model=create_cnn,
    verbose=0
)

param_dist = {

    "model__filters":[16,32,64],

    "model__kernel_size":[3,5],

    "batch_size":[32,64],

    "epochs":[2,3],

    "model__optimizer":["adam","rmsprop"]
}

random_search = RandomizedSearchCV(
    estimator=cnn_model,
    param_distributions=param_dist,
    n_iter=5,
    cv=2,
    random_state=42,
    n_jobs=1
)

# Using only 10,000 images for speed
random_search.fit(
    X_train[:10000],
    y_train[:10000]
)

print("Best Parameters:")
print(random_search.best_params_)

print("\nBest Score:")
print(random_search.best_score_)

cnn_model = KerasClassifier(
    model=create_cnn,
    verbose=0
)

param_grid = {

    "model__filters":[16,32],

    "model__kernel_size":[3,5],

    "batch_size":[32,64],

    "epochs":[2,3],

    "model__optimizer":["adam","rmsprop"]
}

grid_search = GridSearchCV(
    estimator=cnn_model,
    param_grid=param_grid,
    cv=2,
    n_jobs=1
)

# Using only 10,000 images for speed
grid_search.fit(
    X_train[:10000],
    y_train[:10000]
)

print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest Score:")
print(grid_search.best_score_)

best_model = grid_search.best_estimator_

test_accuracy = best_model.score(
    X_test,
    y_test
)

print("Test Accuracy:", test_accuracy)