# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lF6FrTHshhBwxOXtHlU14rIHtJueBc21
"""

import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import random
from skimage import exposure
from skimage.util import random_noise
from skimage import transform
from cv2 import resize

img=mpimg.imread('/content/OIP.jpeg')

plt.imshow(img)

#rescaling
img_rescale=resize(img,(200,250))

plt.imshow(img_rescale)

#filping(horizontal/vertical)
#horizontal
horizontal_flip=np.fliplr(img)

plt.imshow(horizontal_flip)

#vertical flip
vertical_flip=np.flipud(img)
plt.imshow(vertical_flip)

#Rotation
#change values and check with all possible
from skimage import transform
trans_img=transform.rotate(img,-45)
plt.imshow(trans_img)

#Adding noise
img_noise=random_noise(img,mode='s&p',clip=True)
plt.imshow(img_noise)

