# -*- coding: utf-8 -*-
"""Activation_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3elVKSwRqGW6whKdqTtq7ry83yub7_R
"""

import numpy as np

# 1. Binary Step Function
def binary_step(x):
    return np.where(x >= 0, 1, 0)

print("--- Binary Step Function ---")
print("Formula: f(x) = 1 if x >= 0, else 0")
inputs = np.arange(-10, 11)
outputs = binary_step(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11}")

# 2. Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

print("\n--- Sigmoid Function ---")
print("Formula: f(x) = 1 / (1 + e^(-x))")
inputs = np.arange(-10, 11, dtype=float)
outputs = sigmoid(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

# 3. Tanh Function
def tanh(x):
    return np.tanh(x)

print("\n--- Tanh Function ---")
print("Formula: f(x) = (e^x - e^(-x)) / (e^x + e^(-x))")
inputs = np.arange(-10, 11, dtype=float)
outputs = tanh(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

# 4. ReLU (Rectified Linear Unit) Function
def relu(x):
    return np.maximum(0, x)

print("\n--- ReLU Function ---")
print("Formula: f(x) = max(0, x)")
inputs = np.arange(-10, 11, dtype=float)
outputs = relu(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

# 5. Leaky ReLU Function
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)

print("\n--- Leaky ReLU Function (alpha=0.01) ---")
print("Formula: f(x) = x if x > 0, else alpha * x")
inputs = np.arange(-10, 11, dtype=float)
outputs = leaky_relu(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

# 6. ELU (Exponential Linear Unit) Function
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

print("\n--- ELU Function (alpha=1.0) ---")
print("Formula: f(x) = x if x > 0, else alpha * (e^x - 1)")
inputs = np.arange(-10, 11, dtype=float)
outputs = elu(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

import matplotlib.pyplot as plt

print("\n--- Task 2: Plotting Activation Functions ---")

x = np.linspace(-10, 10, 400) # Generate 400 points between -10 and 10

# Calculate outputs for each function
y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)
y_leaky_relu = leaky_relu(x)
y_elu = elu(x)
y_swish = swish(x)

# Plotting
plt.figure(figsize=(12, 8))
plt.plot(x, y_sigmoid, label='Sigmoid')
plt.plot(x, y_tanh, label='Tanh')
plt.plot(x, y_relu, label='ReLU')
plt.plot(x, y_leaky_relu, label='Leaky ReLU')
plt.plot(x, y_elu, label='ELU')
plt.plot(x, y_swish, label='Swish')

plt.title('Comparison of Activation Functions')
plt.xlabel('Input (x)')
plt.ylabel('Output f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-2, 2) # Limit y-axis for better visualization of Sigmoid and Tanh
plt.show()

print("\n--- Task 3: Derivative Calculation and Plotting ---")

# Derivatives of the activation functions
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def leaky_relu_derivative(x, alpha=0.01):
    return np.where(x > 0, 1, alpha)

# Generate input range
x_deriv = np.linspace(-10, 10, 400)

# Calculate derivatives
d_sigmoid = sigmoid_derivative(x_deriv)
d_tanh = tanh_derivative(x_deriv)
d_relu = relu_derivative(x_deriv)
d_leaky_relu = leaky_relu_derivative(x_deriv)

# Plotting derivatives
plt.figure(figsize=(12, 8))
plt.plot(x_deriv, d_sigmoid, label='Derivative of Sigmoid')
plt.plot(x_deriv, d_tanh, label='Derivative of Tanh')
plt.plot(x_deriv, d_relu, label='Derivative of ReLU')
plt.plot(x_deriv, d_leaky_relu, label='Derivative of Leaky ReLU')

plt.title('Derivatives of Activation Functions')
plt.xlabel('Input (x)')
plt.ylabel('Derivative f\'(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-0.1, 1.1) # Set y-axis limits for better visualization
plt.show()

import matplotlib.pyplot as plt

print("\n--- Task 2: Plotting Activation Functions ---")

x = np.linspace(-10, 10, 400) # Generate 400 points between -10 and 10

# Calculate outputs for each function
y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)
y_leaky_relu = leaky_relu(x)
y_elu = elu(x)
y_swish = swish(x)

# Plotting
plt.figure(figsize=(12, 8))
plt.plot(x, y_sigmoid, label='Sigmoid')
plt.plot(x, y_tanh, label='Tanh')
plt.plot(x, y_relu, label='ReLU')
plt.plot(x, y_leaky_relu, label='Leaky ReLU')
plt.plot(x, y_elu, label='ELU')
plt.plot(x, y_swish, label='Swish')

plt.title('Comparison of Activation Functions')
plt.xlabel('Input (x)')
plt.ylabel('Output f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-2, 2) # Limit y-axis for better visualization of Sigmoid and Tanh
plt.show()

# 7. Softplus Function
def softplus(x):
    return np.log(1 + np.exp(x))

print("\n--- Softplus Function ---")
print("Formula: f(x) = ln(1 + e^x)")
inputs = np.arange(-10, 11, dtype=float)
outputs = softplus(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

# 8. Swish Function
def swish(x, beta=1.0):
    return x * (1 / (1 + np.exp(-beta * x)))

print("\n--- Swish Function (beta=1.0) ---")
print("Formula: f(x) = x * sigmoid(beta * x)")
inputs = np.arange(-10, 11, dtype=float)
outputs = swish(inputs)
print("Input (x) | Output f(x)")
print("-----------------------")
for i, o in zip(inputs, outputs):
    print(f"{i:9} | {o:11.6f}")

import matplotlib.pyplot as plt

print("\n--- Task 2: Plotting Activation Functions ---")

x = np.linspace(-10, 10, 400) # Generate 400 points between -10 and 10

# Calculate outputs for each function
y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)
y_leaky_relu = leaky_relu(x)
y_elu = elu(x)
y_swish = swish(x)

# Plotting
plt.figure(figsize=(12, 8))
plt.plot(x, y_sigmoid, label='Sigmoid')
plt.plot(x, y_tanh, label='Tanh')
plt.plot(x, y_relu, label='ReLU')
plt.plot(x, y_leaky_relu, label='Leaky ReLU')
plt.plot(x, y_elu, label='ELU')
plt.plot(x, y_swish, label='Swish')

plt.title('Comparison of Activation Functions')
plt.xlabel('Input (x)')
plt.ylabel('Output f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-2, 2) # Limit y-axis for better visualization of Sigmoid and Tanh
plt.show()

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import time

print("\n--- Task 6: Neural Network Experiment (MNIST) ---")
print("Loading and preprocessing MNIST dataset...")

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

print(f"Original x_train shape: {x_train.shape}")
print(f"Original y_train shape: {y_train.shape}")

# Normalize pixel values to 0-1 range
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Reshape images to vectors (28*28 = 784 pixels)
x_train = x_train.reshape(-1, 28 * 28)
x_test = x_test.reshape(-1, 28 * 28)

# Convert labels to one-hot encoding
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)

print(f"x_train (reshaped and normalized) shape: {x_train.shape}")
print(f"y_train (one-hot encoded) shape: {y_train.shape}")
print("Data preprocessing complete.")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Function to create a simple neural network model
def create_model(activation_function):
    model = keras.Sequential([
        layers.Input(shape=(784,)),
        layers.Dense(128, activation=activation_function),
        layers.Dense(64, activation=activation_function),
        layers.Dense(10, activation='softmax') # Output layer for 10 classes
    ])

    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Common training parameters
epochs = 10
batch_size = 32

# Dictionary to store results for comparison
results = {}

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with Sigmoid activation
print(f"\n--- Training with Sigmoid activation ---")
sigmoid_model = create_model('sigmoid')
sigmoid_model.summary()

start_time = time.time()
history_sigmoid = sigmoid_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0 # Suppress verbose output for cleaner display
)
end_time = time.time()
training_time_sigmoid = end_time - start_time

# Evaluate and store results
loss_sigmoid, accuracy_sigmoid = sigmoid_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_sigmoid = history_sigmoid.history['val_accuracy'][-1]

results['sigmoid'] = {
    'accuracy': accuracy_sigmoid,
    'loss': loss_sigmoid,
    'val_accuracy': val_accuracy_sigmoid,
    'training_time': training_time_sigmoid
}

print(f"Sigmoid - Test Accuracy: {accuracy_sigmoid:.4f}, Test Loss: {loss_sigmoid:.4f}, Val Accuracy: {val_accuracy_sigmoid:.4f}, Training Time: {training_time_sigmoid:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with Tanh activation
print(f"\n--- Training with Tanh activation ---")
tanh_model = create_model('tanh')
tanh_model.summary()

start_time = time.time()
history_tanh = tanh_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_tanh = end_time - start_time

# Evaluate and store results
loss_tanh, accuracy_tanh = tanh_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_tanh = history_tanh.history['val_accuracy'][-1]

results['tanh'] = {
    'accuracy': accuracy_tanh,
    'loss': loss_tanh,
    'val_accuracy': val_accuracy_tanh,
    'training_time': training_time_tanh
}

print(f"Tanh - Test Accuracy: {accuracy_tanh:.4f}, Test Loss: {loss_tanh:.4f}, Val Accuracy: {val_accuracy_tanh:.4f}, Training Time: {training_time_tanh:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("\n--- Task 7: Real-world Case Study - Recommended Activation Functions ---")

print("\nRecommendation for Image Classification (e.g., MNIST, CIFAR-10): ReLU or its variants")
print("Justification: ReLU and its variants (Leaky ReLU, ELU, Swish) are widely used in deep convolutional neural networks due to their ability to mitigate vanishing gradients and computational efficiency. The output layer usually employs 'softmax' for multi-class classification.")

def create_cnn_model(input_shape, num_classes, activation_hidden='relu'):
    model = keras.Sequential([
        layers.Conv2D(32, (3, 3), activation=activation_hidden, input_shape=input_shape),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(64, (3, 3), activation=activation_hidden),
        layers.MaxPooling2D((2, 2)),
        layers.Flatten(),
        layers.Dense(128, activation=activation_hidden),
        layers.Dense(num_classes, activation='softmax') # Softmax for multi-class classification
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Example usage (model configuration, not training):
# mnist_input_shape = (28, 28, 1)
# cifar_input_shape = (32, 32, 3)
# image_classifier_relu = create_cnn_model(mnist_input_shape, 10, 'relu')
# print("\nExample Image Classification Model (ReLU hidden, Softmax output):")
# image_classifier_relu.summary()

print("\nRecommendation for Binary Classification (e.g., spam detection): Sigmoid")
print("Justification: For binary classification problems, the sigmoid function is typically used in the output layer to output a probability between 0 and 1, which can be thresholded to predict one of two classes.")

def create_binary_classifier_model(input_dim, activation_hidden='relu'):
    model = keras.Sequential([
        layers.Dense(64, activation=activation_hidden, input_shape=(input_dim,)),
        layers.Dense(32, activation=activation_hidden),
        layers.Dense(1, activation='sigmoid') # Sigmoid for binary classification probability
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Example usage (model configuration):
# input_features = 100
# binary_model_sigmoid = create_binary_classifier_model(input_features, 'relu')
# print("\nExample Binary Classification Model (ReLU hidden, Sigmoid output):")
# binary_model_sigmoid.summary()

print("\nRecommendation for Regression (e.g., House Price Prediction): Linear (no activation) for output layer")
print("Justification: In regression tasks, the goal is to predict a continuous value. Therefore, the output layer typically uses a 'linear' activation function (or no activation at all) to allow for output values across the entire range, without squashing them into a fixed interval like sigmoid or tanh.")

def create_regression_model(input_dim, activation_hidden='relu'):
    model = keras.Sequential([
        layers.Dense(64, activation=activation_hidden, input_shape=(input_dim,)),
        layers.Dense(32, activation=activation_hidden),
        layers.Dense(1, activation='linear') # Linear activation for continuous regression output
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# Example usage (model configuration):
# input_features_reg = 20
# regression_model_linear = create_regression_model(input_features_reg, 'relu')
# print("\nExample Regression Model (ReLU hidden, Linear output):")
# regression_model_linear.summary()

print("\nThese snippets demonstrate common activation function choices for different real-world applications based on their output requirements and training characteristics.")

print("\n--- Project Progress Summary ---")
print("All requested core tasks (1-8) have been successfully completed as per your instructions for 'simple execution only' and 'code snippets only'.")
print("\nRemaining tasks (Task 9: Research Activity and Task 10: Mini Project) involve generating a multi-page report or developing complex, multi-faceted projects. These are beyond the scope of providing 'simple execution only' and 'code snippets only' as initially requested. If you wish to proceed with any specific sub-component of these tasks in a code-centric manner, please provide more specific instructions.")
print("\nThank you for guiding me through this comprehensive project on Activation Functions!")

"""---"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define a generic CNN model builder function
def create_cnn_model(input_shape, num_classes, activation_fn):
    model = keras.Sequential([
        # Convolutional Layer 1
        layers.Conv2D(32, (3, 3), activation=activation_fn, input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        # Convolutional Layer 2
        layers.Conv2D(64, (3, 3), activation=activation_fn),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        # Flatten the output for the dense layers
        layers.Flatten(),

        # Dense Layer 1
        layers.Dense(128, activation=activation_fn),
        layers.BatchNormalization(),
        layers.Dropout(0.5), # Added dropout for regularization

        # Output Layer
        layers.Dense(num_classes, activation='softmax') # Softmax for multi-class classification
    ])

    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Display a summary of the model for ReLU activation (as an example)
print("Example CNN model summary with ReLU activation:")
mnist_input_shape = mnist_x_train.shape[1:]
mnist_num_classes = mnist_y_train.shape[1]

example_model = create_cnn_model(mnist_input_shape, mnist_num_classes, 'relu')
example_model.summary()

print("CNN model architecture defined.")

import time
import pandas as pd

# Define the activation functions to test
activation_functions_to_test = ['sigmoid', 'tanh', 'relu', 'leaky_relu']

# Common training parameters
epochs = 5 # Reduced epochs for quicker execution
batch_size = 128 # Increased batch size for quicker execution

# Dictionary to store results for comparison
results_task10 = {}

print(f"\nStarting training for {len(activation_functions_to_test)} activation functions on MNIST with {epochs} epochs and batch size {batch_size}...")

for activation_fn_name in activation_functions_to_test:
    print(f"\n--- Training with {activation_fn_name} activation ---")

    # Create model with the specified activation function
    model = create_cnn_model(mnist_x_train.shape[1:], mnist_y_train.shape[1], activation_fn_name)

    # model.summary() # Uncomment to see summary for each model

    start_time = time.time()
    history = model.fit(
        mnist_x_train, mnist_y_train,
        epochs=epochs,
        batch_size=batch_size,
        validation_data=(mnist_x_test, mnist_y_test),
        verbose=0 # Suppress verbose output for cleaner display
    )
    end_time = time.time()
    training_time = end_time - start_time

    # Evaluate and store results
    loss, accuracy = model.evaluate(mnist_x_test, mnist_y_test, verbose=0)
    val_accuracy = history.history['val_accuracy'][-1]

    results_task10[activation_fn_name] = {
        'accuracy': accuracy,
        'loss': loss,
        'val_accuracy': val_accuracy,
        'training_time': training_time
    }

    print(f"{activation_fn_name.capitalize()} - Test Accuracy: {accuracy:.4f}, Test Loss: {loss:.4f}, Val Accuracy: {val_accuracy:.4f}, Training Time: {training_time:.2f}s")

print("\nAll models trained and evaluated.")

# Display overall results in a DataFrame
print("\n--- Overall Comparison Table ---")
df_task10_comparison = pd.DataFrame(results_task10).T
display(df_task10_comparison)

import matplotlib.pyplot as plt

print("\n--- Visualizing Comparison Results ---")

metrics_to_plot = ['accuracy', 'val_accuracy', 'loss', 'training_time']

plt.figure(figsize=(18, 5))

for i, metric in enumerate(metrics_to_plot):
    plt.subplot(1, len(metrics_to_plot), i + 1)
    df_task10_comparison[metric].plot(kind='bar', color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])
    plt.title(f'{metric.replace("_", " ").title()} Comparison')
    plt.xlabel('Activation Function')
    plt.ylabel(metric.replace("_", " ").title())
    plt.xticks(rotation=45, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

print("\nObservation: The plots clearly illustrate the differences in performance metrics across the tested activation functions for image classification on the MNIST dataset.")

display(df_task10_comparison[['accuracy', 'val_accuracy']])

import numpy as np
import matplotlib.pyplot as plt

print("\n--- Task 8: Build Your Own Activation Function ---")

# Custom Activation Function: Smooth Linear Softplus (SLS)
# This function aims to combine the linearity of ReLU for positive inputs
# with a smooth, non-zero gradient for negative inputs, inspired by Softplus,
# while ensuring differentiability at x=0.

# Formula:
# f(x) = x                  if x >= 0
# f(x) = 2 * log(1 + e^x)   if x < 0
# The factor of 2 ensures differentiability at x=0, as derivative of x is 1,
# and derivative of log(1+e^x) is sigmoid(x). At x=0, sigmoid(0) = 0.5.
# So, 2 * 0.5 = 1.

def custom_activation_sls(x):
    return np.where(x >= 0, x, 2 * np.log(1 + np.exp(x)))

# Generate input range
x_custom = np.linspace(-10, 10, 400)
y_custom = custom_activation_sls(x_custom)

# Plotting the custom activation function
plt.figure(figsize=(8, 6))
plt.plot(x_custom, y_custom, label='Smooth Linear Softplus (SLS)')
plt.plot(x_custom, relu(x_custom), linestyle='--', alpha=0.7, label='ReLU (for comparison)')

plt.title('Custom Activation Function: Smooth Linear Softplus (SLS)')
plt.xlabel('Input (x)')
plt.ylabel('Output f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-2, 10) # Adjust y-limit for better visualization
plt.show()

print("Custom Activation Function: Smooth Linear Softplus (SLS) has been defined and plotted.")

print("\n--- Task 8: Advantages and Comparison with ReLU ---")

print("Advantages of Smooth Linear Softplus (SLS) compared to ReLU:")
print("1. Smoothness: SLS is a continuously differentiable function across its entire domain, unlike ReLU which has a non-differentiable point at x=0. Smoothness is often beneficial for gradient-based optimization.")
print("2. No 'Dead ReLU' Problem: For negative inputs, SLS provides a non-zero, positive gradient (2 * sigmoid(x)). This ensures that neurons with negative inputs can still learn and contribute to the gradient, mitigating the 'dead ReLU' problem where neurons can get stuck for negative inputs.")

print("Comparison with ReLU:")
print("- Positive Region (x >= 0): Both SLS and ReLU behave identically, returning f(x) = x, which helps avoid vanishing gradients for positive inputs.")
print("- Negative Region (x < 0): SLS provides a smooth, exponentially saturating output with a positive gradient, while ReLU outputs 0 with a zero gradient. This is the key difference in handling negative activations.")
print("- Gradient at x=0: SLS is differentiable at x=0 with a gradient of 1, providing a smooth transition. ReLU has an abrupt change in gradient at x=0 (from 0 to 1). ")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with ReLU activation
print(f"\n--- Training with ReLU activation ---")
relu_model = create_model('relu')
relu_model.summary()

start_time = time.time()
history_relu = relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_relu = end_time - start_time

# Evaluate and store results
loss_relu, accuracy_relu = relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_relu = history_relu.history['val_accuracy'][-1]

results['relu'] = {
    'accuracy': accuracy_relu,
    'loss': loss_relu,
    'val_accuracy': val_accuracy_relu,
    'training_time': training_time_relu
}

print(f"ReLU - Test Accuracy: {accuracy_relu:.4f}, Test Loss: {loss_relu:.4f}, Val Accuracy: {val_accuracy_relu:.4f}, Training Time: {training_time_relu:.2f}s")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import time

# Train with Leaky ReLU activation
print(f"\n--- Training with Leaky ReLU activation ---")
leaky_relu_model = create_model('leaky_relu')
leaky_relu_model.summary()

start_time = time.time()
history_leaky_relu = leaky_relu_model.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(x_test, y_test),
    verbose=0
)
end_time = time.time()
training_time_leaky_relu = end_time - start_time

# Evaluate and store results
loss_leaky_relu, accuracy_leaky_relu = leaky_relu_model.evaluate(x_test, y_test, verbose=0)
val_accuracy_leaky_relu = history_leaky_relu.history['val_accuracy'][-1]

results['leaky_relu'] = {
    'accuracy': accuracy_leaky_relu,
    'loss': loss_leaky_relu,
    'val_accuracy': val_accuracy_leaky_relu,
    'training_time': training_time_leaky_relu
}

print(f"Leaky ReLU - Test Accuracy: {accuracy_leaky_relu:.4f}, Test Loss: {loss_leaky_relu:.4f}, Val Accuracy: {val_accuracy_leaky_relu:.4f}, Training Time: {training_time_leaky_relu:.2f}s")

import pandas as pd
import matplotlib.pyplot as plt

print("\n--- Task 6: Comparison of Neural Network Experiment Results ---")

# Create a DataFrame from the results dictionary
df_nn_comparison = pd.DataFrame(results).T

display(df_nn_comparison)

# Plotting the comparison (e.g., accuracy)
metrics = ['accuracy', 'loss', 'training_time', 'val_accuracy']

plt.figure(figsize=(15, 5))
for i, metric in enumerate(metrics):
    plt.subplot(1, len(metrics), i + 1)
    df_nn_comparison[metric].plot(kind='bar', color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])
    plt.title(f'{metric.replace("_", " ").title()}')
    plt.ylabel(metric.replace("_", " ").title())
    plt.xlabel('Activation Function')
    plt.xticks(rotation=45)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("\nObservation: The comparison table and plots above summarize the performance of the neural networks trained with different activation functions. We can observe their accuracy, loss, and training efficiency.")

import matplotlib.pyplot as plt

print("\n--- Task 5: Vanishing Gradient Analysis ---")

# Generate a wide range of inputs for analysis
x_analysis = np.linspace(-10, 10, 500)

# --- Sigmoid Function Analysis ---
print("\nAnalyzing Sigmoid Function for Saturation and Vanishing Gradients...")
y_sigmoid_analysis = sigmoid(x_analysis)
d_sigmoid_analysis = sigmoid_derivative(x_analysis)

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
plt.plot(x_analysis, y_sigmoid_analysis, label='Sigmoid Function')
plt.title('Sigmoid Function (f(x))')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0.5, color='gray', linestyle=':', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(1, color='black', linestyle='--', linewidth=0.8)

plt.subplot(1, 2, 2)
plt.plot(x_analysis, d_sigmoid_analysis, label='Derivative of Sigmoid', color='orange')
plt.title('Sigmoid Derivative (f\'(x))')
plt.xlabel('x')
plt.ylabel('f\'(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-0.1, 0.3) # Max derivative is 0.25
plt.suptitle('Sigmoid: Function and its Derivative (Observe vanishing gradients at extremes)', fontsize=14)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

print("Observation: The Sigmoid function saturates at inputs far from zero, leading to derivatives close to zero. This is the vanishing gradient problem.")

import matplotlib.pyplot as plt

# --- Tanh Function Analysis ---
print("\nAnalyzing Tanh Function for Saturation and Vanishing Gradients...")
y_tanh_analysis = tanh(x_analysis)
d_tanh_analysis = tanh_derivative(x_analysis)

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
plt.plot(x_analysis, y_tanh_analysis, label='Tanh Function')
plt.title('Tanh Function (f(x))')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(1, color='black', linestyle='--', linewidth=0.8)
plt.axhline(-1, color='black', linestyle='--', linewidth=0.8)

plt.subplot(1, 2, 2)
plt.plot(x_analysis, d_tanh_analysis, label='Derivative of Tanh', color='red')
plt.title('Tanh Derivative (f\'(x))')
plt.xlabel('x')
plt.ylabel('f\'(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-0.1, 1.1) # Max derivative is 1
plt.suptitle('Tanh: Function and its Derivative (Observe vanishing gradients at extremes)', fontsize=14)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

print("Observation: Similar to Sigmoid, Tanh also saturates at extreme inputs, causing its derivative to approach zero, leading to vanishing gradients.")

import matplotlib.pyplot as plt

# --- ReLU Function Analysis ---
print("\nAnalyzing ReLU Function for Dead Neurons...")
y_relu_analysis = relu(x_analysis)
d_relu_analysis = relu_derivative(x_analysis)

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
plt.plot(x_analysis, y_relu_analysis, label='ReLU Function')
plt.title('ReLU Function (f(x))')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)

plt.subplot(1, 2, 2)
plt.plot(x_analysis, d_relu_analysis, label='Derivative of ReLU', color='green')
plt.title('ReLU Derivative (f\'(x))')
plt.xlabel('x')
plt.ylabel('f\'(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-0.1, 1.1) # Derivative is 0 or 1
plt.suptitle('ReLU: Function and its Derivative (Observe dead neurons for x<=0)', fontsize=14)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

print("Observation: For negative inputs, ReLU's derivative is zero. If a neuron's input consistently falls into the negative range, its gradient will be zero, meaning it will stop learning. This is known as the 'dead ReLU' problem.")

import pandas as pd

print("\n--- Task 4: Compare Activation Functions ---")

comparison_data = {
    'Function': [
        'Binary Step',
        'Sigmoid',
        'Tanh',
        'ReLU',
        'Leaky ReLU',
        'ELU',
        'Softplus',
        'Swish',
        'SELU', # Adding SELU and GELU for a more comprehensive comparison
        'GELU'
    ],
    'Output Range': [
        '{0, 1}',
        '(0, 1)',
        '(-1, 1)',
        '[0, inf)',
        '(-inf, inf)',
        '(-alpha, inf)',
        '(0, inf)',
        '(-inf, inf)',
        '(-scale*alpha, inf)',
        '(-inf, inf)'
    ],
    'Shape': [
        'Step-wise',
        'S-shaped',
        'S-shaped (symmetric)',
        'Linear for x>0, 0 for x<=0',
        'Linear (piecewise)',
        'Linear for x>0, exponential for x<=0',
        'Smooth, like ReLU but differentiable',
        'Smooth, self-gated',
        'Scaled exponential linear',
        'Smooth, non-monotonic'
    ],
    'Smoothness': [
        'Non-differentiable at 0',
        'Smooth, differentiable',
        'Smooth, differentiable',
        'Non-differentiable at 0',
        'Non-differentiable at 0',
        'Smooth, differentiable',
        'Smooth, differentiable',
        'Smooth, differentiable',
        'Smooth, differentiable',
        'Smooth, differentiable'
    ],
    'Gradient Behavior': [
        '0 (except at 0)',
        'Vanishing gradients',
        'Vanishing gradients',
        'No vanishing for x>0, Dead ReLU for x<=0',
        'No vanishing (small slope for x<=0)',
        'No vanishing, helps avoid dead neurons',
        'Always positive, no dead ReLU',
        'Adaptive, avoids vanishing for small values',
        'Self-normalizing, addresses vanishing/exploding gradients',
        'Less prone to vanishing, used in Transformers'
    ]
}

# Create DataFrame
df_comparison = pd.DataFrame(comparison_data)
display(df_comparison)

import matplotlib.pyplot as plt

print("\n--- Task 2: Plotting Activation Functions ---")

x = np.linspace(-10, 10, 400) # Generate 400 points between -10 and 10

# Calculate outputs for each function
y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)
y_leaky_relu = leaky_relu(x)
y_elu = elu(x)
y_swish = swish(x)

# Plotting
plt.figure(figsize=(12, 8))
plt.plot(x, y_sigmoid, label='Sigmoid')
plt.plot(x, y_tanh, label='Tanh')
plt.plot(x, y_relu, label='ReLU')
plt.plot(x, y_leaky_relu, label='Leaky ReLU')
plt.plot(x, y_elu, label='ELU')
plt.plot(x, y_swish, label='Swish')

plt.title('Comparison of Activation Functions')
plt.xlabel('Input (x)')
plt.ylabel('Output f(x)')
plt.grid(True)
plt.legend()
plt.axvline(0, color='black', linestyle='--', linewidth=0.8)
plt.axhline(0, color='black', linestyle='--', linewidth=0.8)
plt.ylim(-2, 2) # Limit y-axis for better visualization of Sigmoid and Tanh
plt.show()