# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJptrOG2afkPj615CW1jIuEKw84YCj5Y
"""

txt="Hello, This is Anjali"
print(txt)
#CASE FOLDING

x=txt.casefold()
print(x)

y=txt.lower()
print(y)

#SPECIAL CHARACTER REMOVAL

  #input string
  input_str="hello how  are @you?"

import re

import re
# Remove non-alphanumeric and non-space characters
# Using the input_str defined in cell bg4C9vDJ9yzr ("hello how are you doing!!")
cleaned_str_step1 = re.sub(r'[^a-zA-Z0-9\s]', '', input_str)
# Replace multiple spaces with a single space and strip leading/trailing spaces
clean_str = re.sub(r'\s+', ' ', cleaned_str_step1).strip()
print(clean_str)

#Libraries in the field NLP
#Spacy-Natural  Language processing library in the python taht can be used to tokenize
#NLTK

import spacy
#load the spacy model
nlp=spacy.load('en_core_web_sm')

#input string
input_str="hello how are you doing!!"

#functions to clean the string
def clean_text (text):
  cleaned_text=''.join(char for char in text if char.isalpha() or char.isspace())
  doc=nlp(cleaned_text)
  return ''.join(token.text for token in doc)

#Final Output
clean_str=clean_text(input_str)
print(clean_str)



#With the NLTK
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

#Tokenize
tokens=nltk.word_tokenize(input_str)

#Remove the special characters
clean_tokens=[token for token in tokens if token.isalnum()]

clean_str=''.join(clean_tokens)
print(clean_str)

#Contractions
!pip install Contractions

import contractions
txt="I cant believe its already raining"
expanded_txt=contractions.fix(txt)
print(expanded_txt)

import re
def expand_contartions(text):
  contractions_pattern={
      r"(?i)can't":"cannot",
      r"(?i)won't":"will not",
      r"(?i)n't":"not",
      r"(?i)\'re":"are",
      r"(?i)\'s":"is",
      r"(?i)\'d":"would",
  }
  for contractions,expansion in contractions_pattern.items():
    text=re.sub(contractions,expansion,text)

  return text

txt="I couldn't visit my aunt's place yesterday"
expanded_text=expand_contartions(txt)
print(expanded_text)

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

#Sample sentence
sentence="This is a sample sentence, showing off the stop words filtration"

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
words=word_tokenize(sentence)

#Filter out stopwords
new_sentence=[word for word in words if word.lower() not in stopwords.words('english')]

#print the final
print(sentence)
print(new_sentence)

