# -*- coding: utf-8 -*-
"""NLP_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdvyOHiF1yrmX6dgeKHVYw7qmS-t1L-1
"""

import re
import nltk
from nltk.corpus import stopwords
from collections import Counter
import pandas as pd

# Download NLTK stopwords if not already downloaded
try:
    nltk.data.find('corpora/stopwords')
except nltk.downloader.DownloadError:
    nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

"""## General Text Cleaning Function

This function will perform case folding, contraction expansion, special character removal, stopword removal, and extra space removal. This function will be reused across various tasks.
"""

# The 'contractions' dictionary is already available in the kernel state.

def clean_text_general(text):
    # 1. Case Folding
    text = text.lower()

    # 2. Expand Contractions
    # Use a regex to find all contractions in the text and replace them
    for contraction, expansion in contractions.items():
        text = re.sub(r'\b' + re.escape(contraction) + r'\b', expansion, text)

    # 3. Remove Special Characters (keep alphanumeric and spaces)
    text = re.sub(r'[^a-z0-9\s]', '', text)

    # 4. Remove Stopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]
    text = ' '.join(words)

    # 5. Remove Unnecessary Extra Spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

"""## Practical Task 1: Text Cleaning Pipeline

Here, I'll apply the `clean_text_general` function to the sample input, display the original and cleaned text, and calculate the number of words before and after preprocessing.
"""

sample_input_task1 = "I'm really HAPPY about this product!!! It's amazing & I don't\nthink I've ever used something this good. @product #awesome"

# Clean the text
cleaned_text_task1 = clean_text_general(sample_input_task1)

# Calculate word counts
words_before_task1 = len(sample_input_task1.split())
words_after_task1 = len(cleaned_text_task1.split())

# Display results
print("--- Practical Task 1 Results ---")
print(f"Original Text: {sample_input_task1}")
print(f"Cleaned Text: {cleaned_text_task1}")
print(f"Words Before Preprocessing: {words_before_task1}")
print(f"Words After Preprocessing: {words_after_task1}")

"""## Practical Task 2: Social Media Text Cleaning

This task requires an additional step: removing hashtags and mentions. I'll create a specialized function for this and apply it to the sample social media comments.
"""

def clean_social_media_text(text):
    # Apply general cleaning first
    text = clean_text_general(text)

    # Remove hashtags and mentions
    text = re.sub(r'#\w+', '', text)  # Remove hashtags
    text = re.sub(r'@\w+', '', text)  # Remove mentions

    # Remove any extra spaces that might result from removal
    text = re.sub(r'\s+', ' ', text).strip()
    return text

sample_comments_task2 = [
    "OMG!!! I can't believe this 😍 @user #Amazing",
    "This movie wasn't good... I don't recommend it!!!",
    "I'm LOVING this product!!! It's sooo good 😍"
]

print("--- Practical Task 2 Results ---")
comparison_data = []
for comment in sample_comments_task2:
    cleaned_comment = clean_social_media_text(comment)
    comparison_data.append({"Before Preprocessing": comment, "After Preprocessing": cleaned_comment})

comparison_df = pd.DataFrame(comparison_data)
display(comparison_df)

"""## Practical Task 3: Customer Review Preprocessing

I will apply the general cleaning function to the `df_reviews` DataFrame, create a new `cleaned_review` column, compare the average number of words before and after cleaning, and identify the 10 most frequent words in the cleaned reviews.
"""

# Ensure df_reviews is available. If not, this cell would fail.
# Assuming df_reviews is already loaded as per the kernel state.

# Create a new column for cleaned reviews
df_reviews['cleaned_review'] = df_reviews['review'].apply(clean_text_general)

# Calculate words before and after for each review
df_reviews['words_before'] = df_reviews['review'].apply(lambda x: len(x.split()))
df_reviews['words_after'] = df_reviews['cleaned_review'].apply(lambda x: len(x.split()))

# Compare average number of words
average_words_before_task3 = df_reviews['words_before'].mean()
average_words_after_task3 = df_reviews['words_after'].mean()

print("--- Practical Task 3 Results ---")
print(f"Average words before cleaning: {average_words_before_task3:.2f}")
print(f"Average words after cleaning: {average_words_after_task3:.2f}")

# Identify the 10 most frequent words in cleaned reviews
all_cleaned_words_task3 = ' '.join(df_reviews['cleaned_review']).split()
word_counts_task3 = Counter(all_cleaned_words_task3)
top_10_frequent_words_task3 = word_counts_task3.most_common(10)

print("\nTop 10 most frequent words in cleaned reviews:")
for word, count in top_10_frequent_words_task3:
    print(f"- {word}: {count}")

display(df_reviews.head())

"""## Practical Task 4: News Article Text Cleaning

For news articles, I will apply the general cleaning function, calculate words before and after, identify the 10 most frequent words, the 10 most frequent stopwords, and the percentage reduction in text size.
"""

# Ensure df_news is available. If not, this cell would fail.
# Assuming df_news is already loaded as per the kernel state.

# Create a new column for cleaned articles
df_news['cleaned_article'] = df_news['article'].apply(clean_text_general)

# Calculate words before and after for each article
df_news['words_before'] = df_news['article'].apply(lambda x: len(x.split()))
df_news['words_after'] = df_news['cleaned_article'].apply(lambda x: len(x.split()))

# How many words were present before preprocessing?
total_words_before_task4 = df_news['words_before'].sum()
print("--- Practical Task 4 Results ---")
print(f"Total words before preprocessing: {total_words_before_task4}")

# How many words remained after preprocessing?
total_words_after_task4 = df_news['words_after'].sum()
print(f"Total words after preprocessing: {total_words_after_task4}")

# Which 10 words occur most frequently?
all_cleaned_words_task4 = ' '.join(df_news['cleaned_article']).split()
word_counts_task4 = Counter(all_cleaned_words_task4)
top_10_frequent_words_task4 = word_counts_task4.most_common(10)
print("\nTop 10 most frequent words in cleaned news articles:")
for word, count in top_10_frequent_words_task4:
    print(f"- {word}: {count}")

# Which stopwords appeared most frequently?
# To do this, we need to extract stopwords from the *original* text.
all_original_words_task4 = ' '.join(df_news['article'].str.lower()).split()
original_stopwords_task4 = [word for word in all_original_words_task4 if word in stop_words]
stopwords_counts_task4 = Counter(original_stopwords_task4)
top_10_frequent_stopwords_task4 = stopwords_counts_task4.most_common(10)

print("\nTop 10 most frequent stopwords in original news articles:")
for word, count in top_10_frequent_stopwords_task4:
    print(f"- {word}: {count}")

# How much did the text size reduce after preprocessing?
reduction_percentage_task4 = ((total_words_before_task4 - total_words_after_task4) / total_words_before_task4) * 100
print(f"\nText size reduction after preprocessing: {reduction_percentage_task4:.2f}%")

display(df_news.head())