# -*- coding: utf-8 -*-
"""CIFAR_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKnWIDBFpNtf1hiZR-IDK37onP_HUttk
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Dropout,
    BatchNormalization
)

from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from tensorflow.keras.datasets import cifar10

# Automatically downloads CIFAR-10 dataset
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

print("Training Images :", X_train.shape[0])
print("Testing Images :", X_test.shape[0])
print("Image Shape :", X_train.shape[1:])

print("Number of Classes :", len(np.unique(y_train)))

print("Image Size :", X_train.shape[1:])

print("Number of Training Images :", X_train.shape[0])

print("Number of Testing Images :", X_test.shape[0])

class_names = [
    "Airplane",
    "Automobile",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Ship",
    "Truck"
]

print("Class Names")

for i,name in enumerate(class_names):
    print(i,"-",name)

plt.figure(figsize=(15,5))

for i in range(10):

    plt.subplot(2,5,i+1)

    plt.imshow(X_train[i])

    plt.title(class_names[y_train[i][0]])

    plt.axis("off")

plt.show()

X_train = X_train.astype("float32") / 255.0

X_test = X_test.astype("float32") / 255.0

print("Normalization Completed")

y_train_cat = to_categorical(y_train,10)

y_test_cat = to_categorical(y_test,10)

print("One Hot Encoding Completed")

print("X_train Shape :",X_train.shape)

print("X_test Shape :",X_test.shape)

print("y_train Shape :",y_train_cat.shape)

print("y_test Shape :",y_test_cat.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

cnn_model = Sequential()

cnn_model.add(
    Conv2D(
        16,
        (3,3),
        activation='relu',
        input_shape=(32,32,3)
    )
)

cnn_model.add(
    MaxPooling2D((2,2))
)

cnn_model.add(
    Conv2D(
        32,
        (3,3),
        activation='relu'
    )
)

cnn_model.add(
    MaxPooling2D((2,2))
)

cnn_model.add(
    Flatten()
)

cnn_model.add(
    Dense(
        64,
        activation='relu'
    )
)

cnn_model.add(
    Dense(
        10,
        activation='softmax'
    )
)

cnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

cnn_model.summary()

history = cnn_model.fit(
    X_train,
    y_train_cat,
    validation_data=(X_test,y_test_cat),
    epochs=8,
    batch_size=64,
    verbose=1
)

train_loss, train_acc = cnn_model.evaluate(
    X_train,
    y_train_cat,
    verbose=0
)

test_loss, test_acc = cnn_model.evaluate(
    X_test,
    y_test_cat,
    verbose=0
)

print("Training Accuracy :", train_acc)

print("Testing Accuracy :", test_acc)

print("Training Loss :", train_loss)

print("Testing Loss :", test_loss)

difference = train_acc - test_acc

print("Accuracy Difference :", difference)

if difference > 0.10:
    print("Model is Overfitting")

elif train_acc < 0.70 and test_acc < 0.70:
    print("Model is Underfitting")

else:
    print("Model is Well Fitted")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title("Training Accuracy vs Validation Accuracy")

plt.xlabel("Epochs")

plt.ylabel("Accuracy")

plt.legend()

plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title("Training Loss vs Validation Loss")

plt.xlabel("Epochs")

plt.ylabel("Loss")

plt.legend()

plt.show()

predictions = cnn_model.predict(X_test)

predicted_classes = np.argmax(
    predictions,
    axis=1
)

actual_classes = y_test.flatten()

plt.figure(figsize=(15,8))

for i in range(10):

    plt.subplot(2,5,i+1)

    plt.imshow(X_test[i])

    actual = class_names[
        actual_classes[i]
    ]

    predicted = class_names[
        predicted_classes[i]
    ]

    if actual == predicted:
        color = 'green'
    else:
        color = 'red'

    plt.title(
        f"A:{actual}\nP:{predicted}",
        color=color
    )

    plt.axis('off')

plt.show()

from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping

improved_model = Sequential()

improved_model.add(
    Conv2D(
        16,
        (3,3),
        activation='relu',
        input_shape=(32,32,3)
    )
)

improved_model.add(
    MaxPooling2D((2,2))
)

improved_model.add(
    Conv2D(
        32,
        (3,3),
        activation='relu'
    )
)

improved_model.add(
    MaxPooling2D((2,2))
)

improved_model.add(
    Conv2D(
        64,
        (3,3),
        activation='relu'
    )
)

improved_model.add(
    MaxPooling2D((2,2))
)

improved_model.add(
    Dropout(0.3)
)

improved_model.add(
    Flatten()
)

improved_model.add(
    Dense(
        128,
        activation='relu'
    )
)

improved_model.add(
    Dense(
        10,
        activation='softmax'
    )
)

improved_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

history2 = improved_model.fit(
    X_train,
    y_train_cat,
    validation_data=(X_test,y_test_cat),
    epochs=12,
    batch_size=64,
    callbacks=[early_stop],
    verbose=1
)

new_loss, new_acc = improved_model.evaluate(
    X_test,
    y_test_cat,
    verbose=0
)

print("Old Accuracy :", test_acc)

print("New Accuracy :", new_acc)

from sklearn.metrics import confusion_matrix
import seaborn as sns

pred = improved_model.predict(X_test)

pred_classes = np.argmax(
    pred,
    axis=1
)

cm = confusion_matrix(
    actual_classes,
    pred_classes
)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

from sklearn.metrics import classification_report

print(
    classification_report(
        actual_classes,
        pred_classes,
        target_names=class_names
    )
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.layers import Dropout, BatchNormalization

improved_model = Sequential()

# Block 1
improved_model.add(
    Conv2D(
        32,
        (3,3),
        activation='relu',
        padding='same',
        input_shape=(32,32,3)
    )
)

improved_model.add(BatchNormalization())

improved_model.add(MaxPooling2D((2,2)))

# Block 2
improved_model.add(
    Conv2D(
        64,
        (3,3),
        activation='relu',
        padding='same'
    )
)

improved_model.add(BatchNormalization())

improved_model.add(MaxPooling2D((2,2)))

# Block 3
improved_model.add(
    Conv2D(
        128,
        (3,3),
        activation='relu',
        padding='same'
    )
)

improved_model.add(BatchNormalization())

improved_model.add(MaxPooling2D((2,2)))

improved_model.add(Dropout(0.3))

# Fully Connected
improved_model.add(Flatten())

improved_model.add(
    Dense(
        256,
        activation='relu'
    )
)

improved_model.add(Dropout(0.5))

improved_model.add(
    Dense(
        10,
        activation='softmax'
    )
)

from tensorflow.keras.optimizers import Adam

improved_model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=3,
    restore_best_weights=True
)

history2 = improved_model.fit(
    X_train,
    y_train_cat,
    validation_data=(X_test,y_test_cat),
    epochs=20,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

new_loss, new_acc = improved_model.evaluate(
    X_test,
    y_test_cat,
    verbose=0
)

print("Improved Accuracy :", new_acc)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    zoom_range=0.1
)

datagen.fit(X_train)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Dropout, BatchNormalization

model = Sequential()

# Block 1
model.add(Conv2D(32,(3,3),padding='same',
                 activation='relu',
                 input_shape=(32,32,3)))
model.add(BatchNormalization())

model.add(Conv2D(32,(3,3),padding='same',
                 activation='relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))

# Block 2
model.add(Conv2D(64,(3,3),padding='same',
                 activation='relu'))
model.add(BatchNormalization())

model.add(Conv2D(64,(3,3),padding='same',
                 activation='relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))

# Block 3
model.add(Conv2D(128,(3,3),padding='same',
                 activation='relu'))
model.add(BatchNormalization())

model.add(Conv2D(128,(3,3),padding='same',
                 activation='relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.3))

model.add(Flatten())

model.add(Dense(512,activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(10,activation='softmax'))

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import ReduceLROnPlateau

lr_scheduler = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    verbose=1
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    datagen.flow(
        X_train,
        y_train_cat,
        batch_size=32
    ),
    epochs=40,
    validation_data=(X_test,y_test_cat),
    callbacks=[
        early_stop,
        lr_scheduler
    ]
)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Predict test images
predictions = model.predict(X_test)

# Convert probabilities to class labels
predicted_classes = np.argmax(predictions, axis=1)

# Actual labels
actual_classes = np.argmax(y_test_cat, axis=1)

# Confusion Matrix
cm = confusion_matrix(actual_classes, predicted_classes)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.show()

from sklearn.metrics import classification_report

class_names = [
    "Airplane",
    "Automobile",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Ship",
    "Truck"
]

print(
    classification_report(
        actual_classes,
        predicted_classes,
        target_names=class_names
    )
)

