# -*- coding: utf-8 -*-
"""Stock_Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVXcjfNVPnARreuODV_P8ZsIrW1nRkz3
"""

#import libraries
import numpy as np
import matplotlib.pyplot as plts
import pandas as pd

#importing
dataset_train=pd.read_csv('/content/NSE-TATAGLOBAL.csv')
training_set=dataset_train.iloc[:,1:2].values

dataset_train.head()

dataset_train.shape

#feature scaling
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))
training_set_scaled=sc.fit_transform(training_set)

dataset_train.shape

training_set_scaled.shape

#creating the data structure with 60 timesatmps and 1 output
x_train=[]
y_train=[]
for i in range(60,1258):
  x_train.append(training_set_scaled[i-60:i,0])
  y_train.append(training_set_scaled[i,0])
x_train,y_train =np.array(x_train),np.array(y_train)

dataset_train.shape

x_train.shape

x_train.shape[0]

x_train.shape[1]

#Reshaping
x_train=np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))

x_train.shape

#Part -2 building RNN
#import keras libraies aand some of packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

input_shape=(x_train.shape[1],1)

input_shape

x_train.shape[1]

#initializing the RNN
from keras.layers import Input
regressor=Sequential()
regressor.add(Input(shape=(x_train.shape[1], 1)))
#units:50,100,200,256,512,1024
#Adding the first LSTM layer and some Droupout regulrization
regressor.add(LSTM(units=50,return_sequences=True))
regressor.add(Dropout(0.2))

#Adding a second LSTM layer and some Droupout regu;llarization
regressor.add(LSTM(units=50,return_sequences=True))
regressor.add(Dropout(0.2))

#Adding a third LSTM layer and some Droupout regularization
regressor.add(LSTM(units=50,return_sequences=True))
regressor.add(Dropout(0.2))

#Adding fourth layer
regressor.add(LSTM(units=50))
regressor.add(Dropout(0.2))

#adding the output layer
regressor.add(Dense(units=1))

#compiling the RNN
regressor.compile(optimizer='adam',loss='mean_squared_error')

#FITTING THE RNN
regressor.fit(x_train,y_train,epochs=50,batch_size=32)

#Part 3 making the predictions and visualizing the results
dataset_test=pd.read_csv('/content/tatatest.csv')
real_stock_price=dataset_test.iloc[:,1:2].values

dataset_test.shape

real_stock_price

#getting the predicted stock price of december
# The 'dataset_test' variable in the current kernel state is a Series. 2027
dataset_total = pd.concat((dataset_train['Open'], temp_dataset_test_df['Open']), axis=0)

dataset_total

inputs = dataset_total[len(dataset_total) - len(temp_dataset_test_df) - 60:].values
len(inputs)

inputs=inputs.reshape(-1,1)
inputs=sc.transform(inputs)
x_test=[]
for i in range(60,76):
  x_test.append(inputs[i-60:i,0])

len(x_test)

x_test=np.array(x_test)
x_test=np.reshape(x_test,(x_test.shape[0],x_test.shape[1],1))
prediction_stock_price=regressor.predict(x_test)
prediction_stock_price=sc.inverse_transform(prediction_stock_price)

real_stock_price

#visualiozation the results

plt.plot(real_stock_price,color='red',label='Real Stock Price')
plt.plot(prediction_stock_price,color='blue',label='Predicted Stock Price')
plt.title('Stock Price Prediction')
plt.xlabel('Time')
plt.ylabel('Stock Price')
plt.legend()
plt.show()

