# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KboZPIcUHwsEM4ENseUUQ3T_B9S-Gu6
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv('/content/Churn_Modelling (2).csv')
x=df.iloc[:,3:13].values
y=df.iloc[:,13].values

df.head()

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x_1=LabelEncoder()
x[:,1]=labelencoder_x_1.fit_transform(x[:,1])
Labelencoder_x2=LabelEncoder()
x[:,2]=Labelencoder_x2.fit_transform(x[:,2])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

len(df)

len(x_test)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,pred)
print(cm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

pip install keras

pip install tensorflow

import keras
from keras.models import Sequential
from keras.layers import Dense

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_A = Sequential()
classifier_A.add(Input(shape=(x_train.shape[1],)))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

len(x_train)

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred_ann=classifier_A.predict(x_test)
y_pred_ann=(y_pred_ann>0.5).flatten()
cm3=confusion_matrix(y_test,y_pred_ann)
print(cm3)

from sklearn.metrics import accuracy_score
score3=accuracy_score(y_test,y_pred_ann)
print(score3)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_A = Sequential()
classifier_A.add(Input(shape=(x_train.shape[1],)))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

len(x_train)

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred_ann=classifier_A.predict(x_test)
y_pred_ann=(y_pred_ann>0.5).flatten()
cm3=confusion_matrix(y_test,y_pred_ann)
print(cm3)

from sklearn.metrics import accuracy_score
score3=accuracy_score(y_test,y_pred_ann)
print(score3)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_A = Sequential()
classifier_A.add(Input(shape=(x_train.shape[1],)))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

len(x_train)

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred_ann=classifier_A.predict(x_test)
y_pred_ann=(y_pred_ann>0.5).flatten()
cm3=confusion_matrix(y_test,y_pred_ann)
print(cm3)

from sklearn.metrics import accuracy_score
score3=accuracy_score(y_test,y_pred_ann)
print(score3)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_A = Sequential()
classifier_A.add(Input(shape=(x_train.shape[1],)))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier_A.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

len(x_train)

classifier_A.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_A.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred_ann=classifier_A.predict(x_test)
y_pred_ann=(y_pred_ann>0.5).flatten()
cm3=confusion_matrix(y_test,y_pred_ann)
print(cm3)

from sklearn.metrics import accuracy_score
score3=accuracy_score(y_test,y_pred_ann)
print(score3)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_N = Sequential()
classifier_N.add(Input(shape=(x_train.shape[1],)))
classifier_N.add(Dense(units=4,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=4,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=4,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=4,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=4,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_N.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_N.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_N.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_N = Sequential()
classifier_N.add(Input(shape=(x_train.shape[1],)))
classifier_N.add(Dense(units=8,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=8,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=8,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=8,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=8,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_N.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_N.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_N.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_N = Sequential()
classifier_N.add(Input(shape=(x_train.shape[1],)))
classifier_N.add(Dense(units=16,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=16,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=16,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=16,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=16,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_N.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_N.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_N.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_N = Sequential()
classifier_N.add(Input(shape=(x_train.shape[1],)))
classifier_N.add(Dense(units=32,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=32,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=32,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=32,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=32,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_N.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_N.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_N.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_N = Sequential()
classifier_N.add(Input(shape=(x_train.shape[1],)))
classifier_N.add(Dense(units=64,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=64,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=64,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=64,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=64,kernel_initializer='uniform',activation='relu'))
classifier_N.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_N.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_N.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_N.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_K = Sequential()
classifier_K.add(Input(shape=(x_train.shape[1],)))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='sigmoid'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='sigmoid'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='sigmoid'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='sigmoid'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='sigmoid'))
classifier_K.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_K.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_K.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_K.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_K = Sequential()
classifier_K.add(Input(shape=(x_train.shape[1],)))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='tanh'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='tanh'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='tanh'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='tanh'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='tanh'))
classifier_K.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_K.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_K.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_K.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input # Added Input here

classifier_K = Sequential()
classifier_K.add(Input(shape=(x_train.shape[1],)))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='elu'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='elu'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='elu'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='elu'))
classifier_K.add(Dense(units=6,kernel_initializer='uniform',activation='elu'))
classifier_K.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_K.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_K.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_K.predict(x_test)
y_pred = (y_pred > 0.5)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input, LeakyReLU # Added LeakyReLU here

classifier_K = Sequential()
classifier_K.add(Input(shape=(x_train.shape[1],)))
classifier_K.add(Dense(units=6,kernel_initializer='uniform'))
classifier_K.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_K.add(Dense(units=6,kernel_initializer='uniform'))
classifier_K.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_K.add(Dense(units=6,kernel_initializer='uniform'))
classifier_K.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_K.add(Dense(units=6,kernel_initializer='uniform'))
classifier_K.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_K.add(Dense(units=6,kernel_initializer='uniform'))
classifier_K.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_K.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_K.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_K.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_K.predict(x_test)
y_pred = (y_pred > 0.5).flatten()
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
score5=accuracy_score(y_test,y_pred)
print(score5)

from keras.models import Sequential
from keras.layers import Dense, Input, LeakyReLU # Added LeakyReLU here

classifier_H = Sequential()
classifier_H.add(Input(shape=(x_train.shape[1],)))
classifier_H.add(Dense(units=6,kernel_initializer='uniform'))
classifier_H.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_H.add(Dense(units=6,kernel_initializer='uniform'))
classifier_H.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_H.add(Dense(units=6,kernel_initializer='uniform'))
classifier_H.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_H.add(Dense(units=6,kernel_initializer='uniform'))
classifier_H.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_H.add(Dense(units=6,kernel_initializer='uniform'))
classifier_H.add(LeakyReLU(negative_slope=0.01)) # Added LeakyReLU layer
classifier_H.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

classifier_H.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier_H.fit(x_train,y_train,batch_size=10,epochs=50)

y_pred = classifier_H.predict(x_test)
y_pred = (y_pred > 0.5).flatten()
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)

from sklearn.metrics import accuracy_score
socre5=accuracy_score(y_test,y_pred)
print(socre5)

from keras.models import Sequential
from keras.layers import Dense
import time

for init in ['he_uniform','he_normal','glorot_uniform',
             'glorot_normal','random_normal']:

    model = Sequential()

    model.add(Dense(6,
                    activation='relu',
                    kernel_initializer=init,
                    input_dim=x_train.shape[1]))

    model.add(Dense(1,
                    activation='sigmoid'))

    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    start = time.time()

    history = model.fit(x_train,
                        y_train,
                        epochs=50,
                        batch_size=10,
                        verbose=0)

    end = time.time()

    print("\n", init)
    print("Initial Loss:", round(history.history['loss'][0],4))
    print("Final Accuracy:", round(history.history['accuracy'][-1],4))
    print("Training Time:", round(end-start,2),"sec")

from keras.models import Sequential
from keras.layers import Dense

activations = ['sigmoid', 'softmax', 'linear']

for act in activations:

    model = Sequential()

    model.add(Dense(6,
                    activation='relu',
                    input_dim=x_train.shape[1]))

    model.add(Dense(1,
                    activation=act))

    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    history = model.fit(x_train,
                        y_train,
                        epochs=50,
                        batch_size=10,
                        verbose=0)

    print("\nActivation =", act)
    print("Accuracy =", round(history.history['accuracy'][-1],4))
    print("Loss =", round(history.history['loss'][-1],4))

from keras.models import Sequential
from keras.layers import Dense

optimizers = ['adam', 'sgd', 'rmsprop', 'adagrad', 'nadam']

for opt in optimizers:

    model = Sequential()

    model.add(Dense(6,
                    activation='relu',
                    input_dim=x_train.shape[1]))

    model.add(Dense(1,
                    activation='sigmoid'))

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        x_train,
        y_train,
        epochs=50,
        batch_size=10,
        verbose=0
    )

    print("\nOptimizer =", opt)
    print("Accuracy =", round(history.history['accuracy'][-1],4))
    print("Loss =", round(history.history['loss'][-1],4))

from keras.models import Sequential
from keras.layers import Dense

epochs_list = [10, 25, 50, 100, 200]

for ep in epochs_list:

    model = Sequential()

    model.add(Dense(6,
                    activation='relu',
                    input_dim=x_train.shape[1]))

    model.add(Dense(1,
                    activation='sigmoid'))

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        x_train,
        y_train,
        epochs=ep,
        batch_size=10,
        validation_data=(x_test,y_test),
        verbose=0
    )

    print("\nEpochs =", ep)
    print("Accuracy =", round(history.history['accuracy'][-1],4))
    print("Loss =", round(history.history['loss'][-1],4))

from keras.models import Sequential
from keras.layers import Dense

batch_sizes = [8, 16, 32, 64, 128]

for bs in batch_sizes:

    model = Sequential()

    model.add(Dense(6,
                    activation='relu',
                    input_dim=x_train.shape[1]))

    model.add(Dense(1,
                    activation='sigmoid'))

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        x_train,
        y_train,
        epochs=50,
        batch_size=bs,
        validation_data=(x_test, y_test),
        verbose=0
    )

    print("\nBatch Size =", bs)
    print("Accuracy =", round(history.history['accuracy'][-1],4))
    print("Loss =", round(history.history['loss'][-1],4))

from keras.models import Sequential
from keras.layers import Dense, Dropout

classifier = Sequential()

classifier.add(Dense(32,
                     activation='relu',
                     input_dim=x_train.shape[1]))

classifier.add(Dropout(0.2))

classifier.add(Dense(16,
                     activation='relu'))

classifier.add(Dense(1,
                     activation='sigmoid'))

classifier.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = classifier.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_data=(x_test, y_test)
)

print("Accuracy =", history.history['accuracy'][-1])

from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

classifier = Sequential()

classifier.add(Dense(64,
                     activation='relu',
                     input_dim=x_train.shape[1]))

classifier.add(Dropout(0.2))

classifier.add(Dense(32,
                     activation='relu'))

classifier.add(Dropout(0.2))

classifier.add(Dense(16,
                     activation='relu'))

classifier.add(Dense(1,
                     activation='sigmoid'))

classifier.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

classifier.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16,
    verbose=1
)

y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision :", precision_score(y_test,y_pred))
print("Recall :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))

cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred
)

plt.show()

