# -*- coding: utf-8 -*-
"""NLP(Spam).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZD30k52WeYDR_uaEb8oAk7B-Yakeekg
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report

df=pd.read_csv('/content/spam.csv')

df.head()

df.tail()

df.Category.value_counts()

df.Category.value_counts()/len(df)*100

df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

df.head()

new_df=pd.read_csv('/content/spam.csv')

new_df['Category'].replace({'ham':0,'spam':1},inplace=True)

new_df.head(5)

df.shape

#TRAIN AND TEST SPLIT
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

x_train.shape

x_test.shape

x_train[:4]

y_train[:4]

#CREATE A BAG OF WORDS REPRESENTING USING COUNTVECTORIZE
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
x_test_cv=v.transform(x_test)

x_train_cv

x_train_cv.toarray()[:2][0]

x_train_cv.shape

v.get_feature_names_out()[1771]

v.vocabulary_

x_train_np=x_train_cv.toarray()
x_train_np[0]

np.where(x_train_np[0]!=0)

#NAVIE BAYES CLASSIFIER
model=MultinomialNB()
model.fit(x_train_cv,y_train)

y_pred=model.predict(x_test_cv)

print(classification_report(y_test,y_pred))

message=['Biggest exclusive sale with gift vochers and with gold coins']

message_cnt = v.transform(message)

model.predict(message_cnt)

